version: "3"

services:
  nginx:
    image: nginx:1.20
    volumes:
      - ./src:/home/src
      - ./logs:/home/logs
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${PORT}:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./src:/home/src
    working_dir: /home/src
    environment:
      UID: ${UID}
      GID: ${GID}
    user: ${UID}:${GID}

  node:
    image: node:16.15.1
    volumes:
      - ./src:/home/src
    working_dir: /home/src
